// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/grpc/v1/sign_in.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SignInService_SignInInit_FullMethodName     = "/v1.SignInService/SignInInit"
	SignInService_SignInFinalize_FullMethodName = "/v1.SignInService/SignInFinalize"
)

// SignInServiceClient is the client API for SignInService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignInServiceClient interface {
	SignInInit(ctx context.Context, in *SignInInitRequest, opts ...grpc.CallOption) (*SignInInitResponse, error)
	SignInFinalize(ctx context.Context, in *SignInFinalizeRequest, opts ...grpc.CallOption) (*SignInFinalizeResponse, error)
}

type signInServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignInServiceClient(cc grpc.ClientConnInterface) SignInServiceClient {
	return &signInServiceClient{cc}
}

func (c *signInServiceClient) SignInInit(ctx context.Context, in *SignInInitRequest, opts ...grpc.CallOption) (*SignInInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInInitResponse)
	err := c.cc.Invoke(ctx, SignInService_SignInInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signInServiceClient) SignInFinalize(ctx context.Context, in *SignInFinalizeRequest, opts ...grpc.CallOption) (*SignInFinalizeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignInFinalizeResponse)
	err := c.cc.Invoke(ctx, SignInService_SignInFinalize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignInServiceServer is the server API for SignInService service.
// All implementations must embed UnimplementedSignInServiceServer
// for forward compatibility.
type SignInServiceServer interface {
	SignInInit(context.Context, *SignInInitRequest) (*SignInInitResponse, error)
	SignInFinalize(context.Context, *SignInFinalizeRequest) (*SignInFinalizeResponse, error)
	mustEmbedUnimplementedSignInServiceServer()
}

// UnimplementedSignInServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignInServiceServer struct{}

func (UnimplementedSignInServiceServer) SignInInit(context.Context, *SignInInitRequest) (*SignInInitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignInInit not implemented")
}
func (UnimplementedSignInServiceServer) SignInFinalize(context.Context, *SignInFinalizeRequest) (*SignInFinalizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignInFinalize not implemented")
}
func (UnimplementedSignInServiceServer) mustEmbedUnimplementedSignInServiceServer() {}
func (UnimplementedSignInServiceServer) testEmbeddedByValue()                       {}

// UnsafeSignInServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignInServiceServer will
// result in compilation errors.
type UnsafeSignInServiceServer interface {
	mustEmbedUnimplementedSignInServiceServer()
}

func RegisterSignInServiceServer(s grpc.ServiceRegistrar, srv SignInServiceServer) {
	// If the following call pancis, it indicates UnimplementedSignInServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignInService_ServiceDesc, srv)
}

func _SignInService_SignInInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignInServiceServer).SignInInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignInService_SignInInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignInServiceServer).SignInInit(ctx, req.(*SignInInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignInService_SignInFinalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignInFinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignInServiceServer).SignInFinalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignInService_SignInFinalize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignInServiceServer).SignInFinalize(ctx, req.(*SignInFinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignInService_ServiceDesc is the grpc.ServiceDesc for SignInService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignInService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SignInService",
	HandlerType: (*SignInServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignInInit",
			Handler:    _SignInService_SignInInit_Handler,
		},
		{
			MethodName: "SignInFinalize",
			Handler:    _SignInService_SignInFinalize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/v1/sign_in.proto",
}
