// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: api/grpc/v1/sign_in.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignInInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SignInInitRequest) Reset() {
	*x = SignInInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_in_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInInitRequest) ProtoMessage() {}

func (x *SignInInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_in_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInInitRequest.ProtoReflect.Descriptor instead.
func (*SignInInitRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_in_proto_rawDescGZIP(), []int{0}
}

func (x *SignInInitRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignInInitRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *SignInInitResponse) Reset() {
	*x = SignInInitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_in_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInInitResponse) ProtoMessage() {}

func (x *SignInInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_in_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInInitResponse.ProtoReflect.Descriptor instead.
func (*SignInInitResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_in_proto_rawDescGZIP(), []int{1}
}

func (x *SignInInitResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SignInFinalizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Otp       string `protobuf:"bytes,2,opt,name=otp,proto3" json:"otp,omitempty"`
}

func (x *SignInFinalizeRequest) Reset() {
	*x = SignInFinalizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_in_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInFinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInFinalizeRequest) ProtoMessage() {}

func (x *SignInFinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_in_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInFinalizeRequest.ProtoReflect.Descriptor instead.
func (*SignInFinalizeRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_in_proto_rawDescGZIP(), []int{2}
}

func (x *SignInFinalizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignInFinalizeRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type SignInFinalizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SignInFinalizeResponse) Reset() {
	*x = SignInFinalizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_in_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInFinalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInFinalizeResponse) ProtoMessage() {}

func (x *SignInFinalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_in_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInFinalizeResponse.ProtoReflect.Descriptor instead.
func (*SignInFinalizeResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_in_proto_rawDescGZIP(), []int{3}
}

var File_api_grpc_v1_sign_in_proto protoreflect.FileDescriptor

var file_api_grpc_v1_sign_in_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69,
	0x67, 0x6e, 0x5f, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22,
	0x45, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x33, 0x0a, 0x12, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e,
	0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x15, 0x53,
	0x69, 0x67, 0x6e, 0x49, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x74, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6f, 0x74, 0x70, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x46,
	0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32,
	0x99, 0x01, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x12,
	0x15, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x49, 0x6e, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x49, 0x0a, 0x0e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x12, 0x19, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x46, 0x69,
	0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_v1_sign_in_proto_rawDescOnce sync.Once
	file_api_grpc_v1_sign_in_proto_rawDescData = file_api_grpc_v1_sign_in_proto_rawDesc
)

func file_api_grpc_v1_sign_in_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_sign_in_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_sign_in_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_v1_sign_in_proto_rawDescData)
	})
	return file_api_grpc_v1_sign_in_proto_rawDescData
}

var file_api_grpc_v1_sign_in_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_grpc_v1_sign_in_proto_goTypes = []interface{}{
	(*SignInInitRequest)(nil),      // 0: v1.SignInInitRequest
	(*SignInInitResponse)(nil),     // 1: v1.SignInInitResponse
	(*SignInFinalizeRequest)(nil),  // 2: v1.SignInFinalizeRequest
	(*SignInFinalizeResponse)(nil), // 3: v1.SignInFinalizeResponse
}
var file_api_grpc_v1_sign_in_proto_depIdxs = []int32{
	0, // 0: v1.SignInService.SignInInit:input_type -> v1.SignInInitRequest
	2, // 1: v1.SignInService.SignInFinalize:input_type -> v1.SignInFinalizeRequest
	1, // 2: v1.SignInService.SignInInit:output_type -> v1.SignInInitResponse
	3, // 3: v1.SignInService.SignInFinalize:output_type -> v1.SignInFinalizeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_sign_in_proto_init() }
func file_api_grpc_v1_sign_in_proto_init() {
	if File_api_grpc_v1_sign_in_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_v1_sign_in_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_in_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInInitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_in_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInFinalizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_in_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInFinalizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_v1_sign_in_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_sign_in_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_sign_in_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_sign_in_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_sign_in_proto = out.File
	file_api_grpc_v1_sign_in_proto_rawDesc = nil
	file_api_grpc_v1_sign_in_proto_goTypes = nil
	file_api_grpc_v1_sign_in_proto_depIdxs = nil
}
