// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        (unknown)
// source: api/grpc/v1/sign_up.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignUpInitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email       string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Login       string `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	SignUpToken string `protobuf:"bytes,4,opt,name=sign_up_token,json=signUpToken,proto3" json:"sign_up_token,omitempty"`
}

func (x *SignUpInitRequest) Reset() {
	*x = SignUpInitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_up_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpInitRequest) ProtoMessage() {}

func (x *SignUpInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_up_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpInitRequest.ProtoReflect.Descriptor instead.
func (*SignUpInitRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_up_proto_rawDescGZIP(), []int{0}
}

func (x *SignUpInitRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpInitRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpInitRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *SignUpInitRequest) GetSignUpToken() string {
	if x != nil {
		return x.SignUpToken
	}
	return ""
}

type SignUpInitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignUpToken           string `protobuf:"bytes,1,opt,name=sign_up_token,json=signUpToken,proto3" json:"sign_up_token,omitempty"`
	SignUpSessionLifetime int64  `protobuf:"varint,3,opt,name=sign_up_session_lifetime,json=signUpSessionLifetime,proto3" json:"sign_up_session_lifetime,omitempty"`
}

func (x *SignUpInitResponse) Reset() {
	*x = SignUpInitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_up_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpInitResponse) ProtoMessage() {}

func (x *SignUpInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_up_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpInitResponse.ProtoReflect.Descriptor instead.
func (*SignUpInitResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_up_proto_rawDescGZIP(), []int{1}
}

func (x *SignUpInitResponse) GetSignUpToken() string {
	if x != nil {
		return x.SignUpToken
	}
	return ""
}

func (x *SignUpInitResponse) GetSignUpSessionLifetime() int64 {
	if x != nil {
		return x.SignUpSessionLifetime
	}
	return 0
}

type SignUpFinalizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignUpToken      string `protobuf:"bytes,1,opt,name=sign_up_token,json=signUpToken,proto3" json:"sign_up_token,omitempty"`
	VerificationCode string `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
}

func (x *SignUpFinalizeRequest) Reset() {
	*x = SignUpFinalizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_up_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpFinalizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpFinalizeRequest) ProtoMessage() {}

func (x *SignUpFinalizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_up_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpFinalizeRequest.ProtoReflect.Descriptor instead.
func (*SignUpFinalizeRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_up_proto_rawDescGZIP(), []int{2}
}

func (x *SignUpFinalizeRequest) GetSignUpToken() string {
	if x != nil {
		return x.SignUpToken
	}
	return ""
}

func (x *SignUpFinalizeRequest) GetVerificationCode() string {
	if x != nil {
		return x.VerificationCode
	}
	return ""
}

type SignUpFinalizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *SignUpFinalizeResponse) Reset() {
	*x = SignUpFinalizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_up_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignUpFinalizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpFinalizeResponse) ProtoMessage() {}

func (x *SignUpFinalizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_up_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpFinalizeResponse.ProtoReflect.Descriptor instead.
func (*SignUpFinalizeResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_up_proto_rawDescGZIP(), []int{3}
}

func (x *SignUpFinalizeResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetOauthSignUpUrlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OauthProvider *string `protobuf:"bytes,1,opt,name=oauth_provider,json=oauthProvider,proto3,oneof" json:"oauth_provider,omitempty"`
}

func (x *GetOauthSignUpUrlRequest) Reset() {
	*x = GetOauthSignUpUrlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_up_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOauthSignUpUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOauthSignUpUrlRequest) ProtoMessage() {}

func (x *GetOauthSignUpUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_up_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOauthSignUpUrlRequest.ProtoReflect.Descriptor instead.
func (*GetOauthSignUpUrlRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_up_proto_rawDescGZIP(), []int{4}
}

func (x *GetOauthSignUpUrlRequest) GetOauthProvider() string {
	if x != nil && x.OauthProvider != nil {
		return *x.OauthProvider
	}
	return ""
}

type GetOauthSignUpUrlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls map[string]string `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetOauthSignUpUrlResponse) Reset() {
	*x = GetOauthSignUpUrlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_up_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOauthSignUpUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOauthSignUpUrlResponse) ProtoMessage() {}

func (x *GetOauthSignUpUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_up_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOauthSignUpUrlResponse.ProtoReflect.Descriptor instead.
func (*GetOauthSignUpUrlResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_up_proto_rawDescGZIP(), []int{5}
}

func (x *GetOauthSignUpUrlResponse) GetUrls() map[string]string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type HandleOauthCallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body        []byte `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	CallbackUrl string `protobuf:"bytes,2,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
}

func (x *HandleOauthCallbackRequest) Reset() {
	*x = HandleOauthCallbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_up_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleOauthCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleOauthCallbackRequest) ProtoMessage() {}

func (x *HandleOauthCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_up_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleOauthCallbackRequest.ProtoReflect.Descriptor instead.
func (*HandleOauthCallbackRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_up_proto_rawDescGZIP(), []int{6}
}

func (x *HandleOauthCallbackRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HandleOauthCallbackRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type HandleOauthCallbackResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *HandleOauthCallbackResponse) Reset() {
	*x = HandleOauthCallbackResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_sign_up_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleOauthCallbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleOauthCallbackResponse) ProtoMessage() {}

func (x *HandleOauthCallbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_sign_up_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleOauthCallbackResponse.ProtoReflect.Descriptor instead.
func (*HandleOauthCallbackResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_sign_up_proto_rawDescGZIP(), []int{7}
}

func (x *HandleOauthCallbackResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

var File_api_grpc_v1_sign_up_proto protoreflect.FileDescriptor

var file_api_grpc_v1_sign_up_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69,
	0x67, 0x6e, 0x5f, 0x75, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x76, 0x31, 0x22,
	0x7f, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x22, 0x0a, 0x0d,
	0x73, 0x69, 0x67, 0x6e, 0x5f, 0x75, 0x70, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x71, 0x0a, 0x12, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x75,
	0x70, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73,
	0x69, 0x67, 0x6e, 0x55, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x37, 0x0a, 0x18, 0x73, 0x69,
	0x67, 0x6e, 0x5f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69,
	0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x15, 0x73, 0x69,
	0x67, 0x6e, 0x55, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x66, 0x65, 0x74,
	0x69, 0x6d, 0x65, 0x22, 0x68, 0x0a, 0x15, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x46, 0x69, 0x6e,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d,
	0x73, 0x69, 0x67, 0x6e, 0x5f, 0x75, 0x70, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x2b, 0x0a, 0x11, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x76, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x37, 0x0a,
	0x16, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x59, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x4f, 0x61, 0x75,
	0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x0e, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x6f, 0x61,
	0x75, 0x74, 0x68, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x88, 0x01, 0x01, 0x42, 0x11,
	0x0a, 0x0f, 0x5f, 0x6f, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65,
	0x72, 0x22, 0x91, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x53, 0x69,
	0x67, 0x6e, 0x55, 0x70, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x55,
	0x70, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x55, 0x72, 0x6c,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x1a, 0x37, 0x0a, 0x09,
	0x55, 0x72, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x53, 0x0a, 0x1a, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4f,
	0x61, 0x75, 0x74, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63,
	0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x55, 0x72, 0x6c, 0x22, 0x3c, 0x0a, 0x1b, 0x48, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32, 0xc8, 0x02, 0x0a, 0x0d, 0x53, 0x69, 0x67,
	0x6e, 0x55, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x53, 0x69,
	0x67, 0x6e, 0x55, 0x70, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x15, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69,
	0x67, 0x6e, 0x55, 0x70, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x49, 0x6e, 0x69, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0e, 0x53, 0x69, 0x67,
	0x6e, 0x55, 0x70, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x12, 0x19, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x55, 0x70, 0x46, 0x69, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x4f, 0x61, 0x75, 0x74, 0x68,
	0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x55, 0x72, 0x6c, 0x73, 0x12, 0x1c, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x55, 0x72, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x13, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x4f, 0x61, 0x75, 0x74, 0x68, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x12, 0x1e, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4f, 0x61, 0x75, 0x74,
	0x68, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x4f, 0x61, 0x75, 0x74,
	0x68, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_grpc_v1_sign_up_proto_rawDescOnce sync.Once
	file_api_grpc_v1_sign_up_proto_rawDescData = file_api_grpc_v1_sign_up_proto_rawDesc
)

func file_api_grpc_v1_sign_up_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_sign_up_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_sign_up_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_v1_sign_up_proto_rawDescData)
	})
	return file_api_grpc_v1_sign_up_proto_rawDescData
}

var file_api_grpc_v1_sign_up_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_grpc_v1_sign_up_proto_goTypes = []interface{}{
	(*SignUpInitRequest)(nil),           // 0: v1.SignUpInitRequest
	(*SignUpInitResponse)(nil),          // 1: v1.SignUpInitResponse
	(*SignUpFinalizeRequest)(nil),       // 2: v1.SignUpFinalizeRequest
	(*SignUpFinalizeResponse)(nil),      // 3: v1.SignUpFinalizeResponse
	(*GetOauthSignUpUrlRequest)(nil),    // 4: v1.GetOauthSignUpUrlRequest
	(*GetOauthSignUpUrlResponse)(nil),   // 5: v1.GetOauthSignUpUrlResponse
	(*HandleOauthCallbackRequest)(nil),  // 6: v1.HandleOauthCallbackRequest
	(*HandleOauthCallbackResponse)(nil), // 7: v1.HandleOauthCallbackResponse
	nil,                                 // 8: v1.GetOauthSignUpUrlResponse.UrlsEntry
}
var file_api_grpc_v1_sign_up_proto_depIdxs = []int32{
	8, // 0: v1.GetOauthSignUpUrlResponse.urls:type_name -> v1.GetOauthSignUpUrlResponse.UrlsEntry
	0, // 1: v1.SignUpService.SignUpInit:input_type -> v1.SignUpInitRequest
	2, // 2: v1.SignUpService.SignUpFinalize:input_type -> v1.SignUpFinalizeRequest
	4, // 3: v1.SignUpService.GetOauthSignUpUrls:input_type -> v1.GetOauthSignUpUrlRequest
	6, // 4: v1.SignUpService.HandleOauthCallback:input_type -> v1.HandleOauthCallbackRequest
	1, // 5: v1.SignUpService.SignUpInit:output_type -> v1.SignUpInitResponse
	3, // 6: v1.SignUpService.SignUpFinalize:output_type -> v1.SignUpFinalizeResponse
	5, // 7: v1.SignUpService.GetOauthSignUpUrls:output_type -> v1.GetOauthSignUpUrlResponse
	7, // 8: v1.SignUpService.HandleOauthCallback:output_type -> v1.HandleOauthCallbackResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_sign_up_proto_init() }
func file_api_grpc_v1_sign_up_proto_init() {
	if File_api_grpc_v1_sign_up_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_v1_sign_up_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpInitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_up_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpInitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_up_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpFinalizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_up_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignUpFinalizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_up_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOauthSignUpUrlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_up_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOauthSignUpUrlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_up_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleOauthCallbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_sign_up_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleOauthCallbackResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_grpc_v1_sign_up_proto_msgTypes[4].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_v1_sign_up_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_sign_up_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_sign_up_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_sign_up_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_sign_up_proto = out.File
	file_api_grpc_v1_sign_up_proto_rawDesc = nil
	file_api_grpc_v1_sign_up_proto_goTypes = nil
	file_api_grpc_v1_sign_up_proto_depIdxs = nil
}
